### PR TITLE
Fix options pane location + update to 1.5.1

### LINKED ISSUE #43: The settings page is empty
Unable to display settings option
image

### PR DESCRIPTION
**Pull request by thebluepotato**
The (very) recent release of 1.5.0 moved the options pane XHTML inside the content folder. As this is cleaner, I changed the code to reflect it. Also a good opportunity to test if updates to 1.5.1 will work! Fixes #43

### CODE REVIEW

**Comment by thebluepotato** [comment]
@bwiernik Sorry for the hassle

**Comment by bwiernik** [comment]
No problem -- I don't have a build script for the .xpi set up on my current machine -- could you make one and post it here?

**Comment by thebluepotato** [comment]
> No problem -- I don't have a build script for the .xpi set up on my current machine -- could you make one and post it here?

I've been updating the BAT script throughout the PR, but I don't have Windows. What's your platform? Would GitHub actions be easier to use? I guess that would allow automation of version numbers across the manifests.

**Comment by bwiernik** [comment]
I'm working on a Mac at this point

**Comment by thebluepotato** [comment]
Ok so do I, I'll draft something over the weekend. In the meantime, if you want to release 1.5.1, you can do the same as you did for .0, namely zip all folders, js files, the JSON manifest, install.rdf and chrome.manifest. I've moved options.xhtml so now it should indeed stay in the content folder.

**Pull request merged**
